name: Update BTC Predictions
on:
  schedule:
    - cron: '20 22 */2 * *'  # Every 2 days at 8AM
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    permissions:
       contents: write
       packages: write
       id-token: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Needed for git operations
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ml_models.txt
    
    - name: Convert Jupyter Notebook to Python script
      run: |
        jupyter nbconvert --to script LSTM_CNN_Prediction_model.ipynb
        jupyter nbconvert --to script XGBoost_Prediction_model.ipynb
    
    - name: Run LSTM CNN model
      run: python LSTM_CNN_Prediction_model.py
    
    - name: Run XGBoost model
      run: python XGBoost_Prediction_model.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name "Action"
        git config --global user.email "${{ secrets.EMAIL }}"
        git add *.csv
        git commit -m "Automated prediction update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Force Streamlit app rebuild
      run: |
        python open_streamlit_app.py
